version: "3.9"
services:
  parabank-baseline:
    image: parasoft/parabank:baseline
    ports:
      - 8090:8080
      - 8050:8050
      - 9021:9001
      - 63616:61616
    environment:
      - TZ=America/Los_Angeles
      - CATALINA_OPTS=-javaagent:"/home/docker/jtest/monitor/agent.jar"=settings="/home/docker/jtest/monitor/agent.properties",runtimeData="/home/docker/jtest/monitor/runtime_coverage"
    volumes:
      - type: bind
        source: C:\Users\whaaker\Downloads\parasoft-docker\parabank-pda-coverage\parabank\target\jtest\monitor\monitor
        target: /home/docker/jtest/monitor
  parasoft-demo-app:
    image: parasoft/demo-app:latest
    ports:
      - 8091:8080
      - 8051:8050
      - 9022:9001
      - 50051:50051
      - 61623:61623
      - 61624:61624
      - 61626:61626
    environment:
      - TZ=America/Los_Angeles
      - CATALINA_OPTS=-javaagent:"/home/docker/jtest/monitor/agent.jar"=settings="/home/docker/jtest/monitor/agent.properties",runtimeData="/home/docker/jtest/monitor/runtime_coverage"
    volumes:
      - type: bind
        source: C:\Users\whaaker\Downloads\parasoft-docker\parabank-pda-coverage\parasoft-demo-app\build\jtest\monitor
        target: /home/docker/jtest/monitor
networks:
  demo-net:
    external: true
    name: demo-net